"""add ticket table

Revision ID: e46a988e8ad2
Revises: 94fde2d87abd
Create Date: 2026-05-25 11:01:50.595037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46a988e8ad2'
down_revision: Union[str, Sequence[str], None] = '94fde2d87abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ticket',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('assigned_to_id', sa.String(length=16), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['Organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Ticket_assigned_to_id'), 'Ticket', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_Ticket_category'), 'Ticket', ['category'], unique=False)
    op.create_index(op.f('ix_Ticket_organization_id'), 'Ticket', ['organization_id'], unique=False)
    op.create_index(op.f('ix_Ticket_priority'), 'Ticket', ['priority'], unique=False)
    op.create_index(op.f('ix_Ticket_status'), 'Ticket', ['status'], unique=False)
    op.create_index(op.f('ix_Ticket_subject'), 'Ticket', ['subject'], unique=False)
    op.create_index(op.f('ix_Ticket_user_id'), 'Ticket', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Ticket_user_id'), table_name='Ticket')
    op.drop_index(op.f('ix_Ticket_subject'), table_name='Ticket')
    op.drop_index(op.f('ix_Ticket_status'), table_name='Ticket')
    op.drop_index(op.f('ix_Ticket_priority'), table_name='Ticket')
    op.drop_index(op.f('ix_Ticket_organization_id'), table_name='Ticket')
    op.drop_index(op.f('ix_Ticket_category'), table_name='Ticket')
    op.drop_index(op.f('ix_Ticket_assigned_to_id'), table_name='Ticket')
    op.drop_table('Ticket')
    # ### end Alembic commands ###
